### ISSUE TITLE
Create subscription is wrong

### ISSUE THREAD

**Issue by laalex** [AuthorizeNet/sample-code-ruby#14]
Create subscription always returns the following error:
```"The element 'subscription' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' cannot contain text. List of possible elements expected: 'name, paymentSchedule, amount, trialAmount, payment, order, customer, billTo, shipTo' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'."```

**Comment by brianmc** [comment]
Should work now @laalex.  You might just need to grab the latest gem 1.8.5.3  Let us know if you still have issues.
