### ISSUE TITLE
Error element in subscription namespace can not contain text !

### ISSUE THREAD

**Issue by brahamshakti** [AuthorizeNet/sample-code-ruby#19]
I don't know why I am getting this error using sample-code-ruby/RecurringBilling/create-subscription.rb

    @text="The element 'subscription' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' cannot contain text. List of possible elements expected: 'name, paymentSchedule, amount, trialAmount, payment, order, customer, billTo, shipTo' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'.

**Comment by brianmc** [comment]
Hi @brahamshakti can you let us know the exact output when you run 
````
ruby RecurringBilling/create-subscription.rb
````
from the root dir

**Comment by brianmc** [comment]
Closing this as I haven't heard back.  Feel free to reopen if the issue persists.

**Comment by kennethjohnbalgos** [comment]
`sample-code-ruby [master] % ruby RecurringBilling/create-subscription.rb
E00003
The element 'subscription' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' cannot contain text. List of possible elements expected: 'name, paymentSchedule, amount, trialAmount, payment, order, customer, billTo, shipTo, profile' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'.
RecurringBilling/create-subscription.rb:48:in `create_Subscription': Failed to create a subscription (RuntimeError)
	from RecurringBilling/create-subscription.rb:55:in `<main>'`

**Comment by kennethjohnbalgos** [comment]
I'm receiving the reported issue.
