### ISSUE TITLE
Is there a way to charge a credit card without the ccv? 

### ISSUE THREAD

**Issue by ChannelJuanNews** [AuthorizeNet/sample-code-ruby#37]
So far the sample code needs to use the ccv, but is there a way we can charge a card without the ccv or is it always required?

**Comment by ashtru** [comment]
According to this discussion [thread](https://community.developer.authorize.net/t5/Integration-and-Testing/Submit-payment-without-the-CVV/td-p/33315), you just need to not pass the card code field, I guess.
Cvv is not required by credit card networks, but only by payment gateway(in this case Authorize.Net).
Authorize.Net provides Recurring Billing, which does not use the credit card CVV after the first charge.
I am not sure whether  simple charge transaction works without CVV, for non-sandbox account.

As a merchant , processing without CVV is a fraud risk in production. So there are settings to define when to accept or reject such transactions in production.  I found a [non-official page]( https://chargify.zendesk.com/hc/en-us/articles/202804434-Authorize-Net-USA-Payment-Gateway-Information-and-Set-Up) describing different options with card code in Authorize.Net.

**Comment by brianmc** [comment]
You can control whether CVV is required on your gateway account by setting the property in the Merchant Interface (https://account.authorize.net or https://sandbox.authorize.net), Settings-> Payment Form -> Form Fields -> Card Code.  If you check the Required box then SDK/API CreateTransaction requests will be rejected unless CVV is supplied.  If this is unchecked then CVV does not need to be sent.  Bear in mind though, as mentioned, CVV is often required by your processor and not passing can impact your interchange (fee) rates.

**Comment by ChannelJuanNews** [comment]
I see, thank you for the reply. I was able to just omit the CVV and it processed just fine.

**Comment by shaileshdwagh** [comment]
i have created the recurring billing setup where ccv was not required to setup the subscription and it worked fine. Now i want to charge the card 1st before setting up recurring subscription.  As per the setting in sandbox  i could see that it would be able to allow all transactions to admin without the ccv and it worked but how do we know how much does it  "impact your interchange (fee) rates." in authorized.net? 
Also , the customer sends the merchant the card details so is it secure to send ccv?
