### ISSUE TITLE
samples are not working

### ISSUE THREAD

**Issue by taf2** [AuthorizeNet/sample-code-ruby#42]
https://github.com/AuthorizeNet/sample-code-ruby/blob/master/TransactionReporting/get-customer-profile-transaction-list.rb#L22

+     request = AuthorizeNet::API::GetTransactionListForCustomerRequest.new

is undefined

**Comment by adavidw** [comment]
Can you give any more information about your environment? Do you have the [Ruby SDK](https://github.com/AuthorizeNet/sdk-ruby) installed?

**Comment by taf2** [comment]
I think we have it working now - it looks like we had an older version of the SDK that we tried on initially and now it's working.

**Comment by adavidw** [comment]
Great, thanks. Let us know if you see anything else in need of attention.
