### ISSUE TITLE
What to give in batchId while sending a request for transaction detail

### ISSUE THREAD

**Issue by shivamkayal** [AuthorizeNet/sample-code-ruby#45]
In the API, Transaction Reporting, we have one option of getting transaction detail, in the specified parameter there is an option of sending **batchID** which is numeric and required field. What do we have to specify in that.

**Comment by adavidw** [comment]
HI @shivamkayal,

Each day, there's a batching process whereby all of the transactions that have been authorized and captured are sent to the merchant's bank for clearing and settlement. Transactions that have been settled are organized in batches on our end.

The [`getSettledBatchListRequest`](https://developer.authorize.net/api/reference/#transaction-reporting-get-settled-batch-list) method will return a list of batch IDs for batches matching the specified parameters. Those batchIds could then be used in the [`getTransactionListRequest`](https://developer.authorize.net/api/reference/#transaction-reporting-get-transaction-list) 
to return the transaction IDs contained within that batch, or used in the [`getBatchStatisticsRequest`](https://developer.authorize.net/api/reference/#transaction-reporting-get-batch-statistics) method to get more information about that batch.
