### ISSUE TITLE
uninitialized constant AuthorizeNet::API::GetTransactionListForCustomerRequest

### ISSUE THREAD

**Issue by shivamkayal** [AuthorizeNet/sample-code-ruby#46]
In the Transaction Reporting, I was trying the API function to get the customer profile transaction list. According to sample code, **AuthorizeNet::API::GetTransactionListForCustomerRequest** is the module which gets the work done. But it doesn't seem to work. It keeps throwing error of uninitialized constant.

**Comment by adavidw** [comment]
How are you calling the method?
Can you post some code?
Are you passing a customer profile ID?
Are you passing the paging and sorting parameters?

**Comment by adavidw** [comment]
Closing due to no response
