### ISSUE TITLE
Why TransactionReporting link not working? 

### ISSUE THREAD

**Issue by brahamshakti** [AuthorizeNet/sample-code-ruby#6]
![screenshot from 2015-10-08 17 51 17](https://cloud.githubusercontent.com/assets/2370848/10366058/64d94f42-6de5-11e5-8b66-41258b9bb1fd.png)
Hi why this link https://api.github.com/repos/AuthorizeNet/sample-code-ruby/contents/TransactionReporting/get-transaction-list.rb for TransactionReporting is not working?

**Comment by brianmc** [comment]
Reporting samples should be there now @brahamshakti 

<img width="825" alt="screen shot 2015-10-10 at 8 46 28 am" src="https://cloud.githubusercontent.com/assets/1022976/10411957/8df1497e-6f2b-11e5-9b79-db893e822042.png">
